---
kind: pipeline
name: test

services:
  - name: mongo
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: sundae
    ports:
      - 27017:27017

steps:
  - name: get-mongodb-version
    image: mongo:4
    commands:
      - date
      - mongo --host mongo --eval "db.version()"

  - name: init-mongodb
    image: mongo:4
    commands:
      - date
      - admin:pwd@mongo:27017/sundae scripts/write.js

  - name: go-test
    image: sundaeparty/devcontainer:latest
    commands:
      - make
      - make go_test
