---
kind: pipeline
name: test

services:
  - name: mongo
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME:
        from_secret: db_admin_user
      MONGO_INITDB_ROOT_PASSWORD:
        from_secret: db_admin_pwd
    ports:
      - 27017
    command: [--replSet, rs0]

steps:
  - name: init-mongodb
    image: mongo:4
    environment:
      DB_ADMIN_USR:
        from_secret: db_admin_user
      DB_ADMIN_PWD:
        from_secret: db_admin_pwd
      DB_USER:
        from_secret: db_user
      DB_PASS:
        from_secret: db_password
      DB_NAME:
        from_secret: db_name
    commands:
      - sleep 15
      - 'mongo --host mongo -u $${DB_ADMIN_USR} -p $${DB_ADMIN_PWD} --eval "rs.initiate({_id: ''rs0'', members: [{_id: 0, host: ''mongo:27017''}]})"'
      - sleep 2
      - 'mongo --host mongo -u $${DB_ADMIN_USR} -p $${DB_ADMIN_PWD} --eval "db.getSiblingDB(''$${DB_NAME}'').createUser({user: ''$${DB_USER}'', pwd: ''$${DB_PASS}'', roles: [{role: ''readWrite'', db: ''$${DB_NAME}''}]})"'

  - name: Check mongo rs conf
    image: mongo:4
    environment:
      DB_ADMIN_USR:
        from_secret: db_admin_user
      DB_ADMIN_PWD:
        from_secret: db_admin_pwd
    commands:
      - mongo --host mongo -u $${DB_ADMIN_USR} -p $${DB_ADMIN_PWD} --eval "rs.status()"

  - name: Gen ssl certificates
    image: alpine:3.13
    volumes:
      - name: ssl
        path: /etc/sundae/ssl
    commands:
      - apk --no-cache add curl
      - curl -JL https://github.com/sundae-party/pki/releases/download/v0.1-beta.1/pki_linux-amd64 -o pki
      - chmod +x ./pki
      - ./pki ca --cn sundae.local --dest /etc/sundae/ssl
      - ./pki serverCert --caCert /etc/sundae/ssl/ca.pem --caKey /etc/sundae/ssl/ca.key --certCn api-server.lan --sansDns=sundae.local,localhost,sundae.com --sansIp=127.0.0.1 --dest /etc/sundae/ssl --certFileName sundae-apiserver.pem --keyFileName sundae-apiserver.key
      - ./pki clientCert --caCert /etc/sundae/ssl/ca.pem --caKey /etc/sundae/ssl/ca.key --certCn integration:mock_integration_test --dest /etc/sundae/ssl --certFileName integration01.pem --keyFileName integration01.key

  - name: Check ssl certificats
    image: alpine:3.13
    volumes:
      - name: ssl
        path: /etc/sundae/ssl
    commands:
      - apk --no-cache add curl
      - curl -JL https://github.com/sundae-party/pki/releases/download/v0.1-beta.1/pki_linux-amd64 -o pki
      - chmod +x ./pki
      - echo "--- CA ---"
      - ./pki read -c /etc/sundae/ssl/ca.pem -k /etc/sundae/ssl/ca.key
      - echo "--- Server ---"
      - ./pki read -c /etc/sundae/ssl/sundae-apiserver.pem -k /etc/sundae/ssl/sundae-apiserver.key
      - echo "--- Client ---"
      - ./pki read -c /etc/sundae/ssl/integration01.pem -k /etc/sundae/ssl/integration01.key

  - name: go-test
    image: sundaeparty/devcontainer:latest
    volumes:
      - name: ssl
        path: /etc/sundae/ssl
    environment:
      MONGO_USR:
        from_secret: db_user
      MONGO_PWD:
        from_secret: db_password
      MONGO_DB:
        from_secret: db_name
      MONGO_ADDR: mongo:27017
      MONGO_RS: rs0
    commands:
      - make
      - make go_test

volumes:
  - name: ssl
    temp: {}
