---
kind: pipeline
name: test

services:
  - name: mongo
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME:
        from_secret: db_admin_user
      MONGO_INITDB_ROOT_PASSWORD:
        from_secret: db_admin_pwd
    ports:
      - 27017

steps:
  - name: get-mongodb-version
    image: mongo:4
    commands:
      - sleep 15
      - date
      - mongo --host mongo --eval "db.version()"

  - name: init-mongodb
    image: mongo:4
    environment:
      DB_ADMIN_USR:
        from_secret: db_admin_user
      DB_ADMIN_PWD:
        from_secret: db_admin_pwd
      DB_USER:
        from_secret: db_user
      DB_PASS:
        from_secret: db_password
      DB_NAME:
        from_secret: db_name
    commands:
      - date
      - mongo --host mongo -u ${DB_ADMIN_USR} -p ${DB_ADMIN_PWD} init_mongo_test.js

  - name: go-test
    image: sundaeparty/devcontainer:latest
    commands:
      - make
      - make go_test
