// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// IntegrationHandlerClient is the client API for IntegrationHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntegrationHandlerClient interface {
	Create(ctx context.Context, in *Integration, opts ...grpc.CallOption) (*Integration, error)
	Get(ctx context.Context, in *Integration, opts ...grpc.CallOption) (*Integration, error)
	Delete(ctx context.Context, in *Integration, opts ...grpc.CallOption) (*Integration, error)
	Update(ctx context.Context, in *Integration, opts ...grpc.CallOption) (*Integration, error)
	Watch(ctx context.Context, in *Integration, opts ...grpc.CallOption) (IntegrationHandler_WatchClient, error)
	CallService(ctx context.Context, in *IntegrationServiceRequest, opts ...grpc.CallOption) (*IntegrationServiceResponse, error)
	WatchService(ctx context.Context, in *Integration, opts ...grpc.CallOption) (IntegrationHandler_WatchServiceClient, error)
	StorePut(ctx context.Context, in *IntegrationStoreRequest, opts ...grpc.CallOption) (*IntegrationStoreRequest, error)
	StoreGet(ctx context.Context, in *IntegrationStoreRequest, opts ...grpc.CallOption) (*IntegrationStoreRequest, error)
}

type integrationHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegrationHandlerClient(cc grpc.ClientConnInterface) IntegrationHandlerClient {
	return &integrationHandlerClient{cc}
}

func (c *integrationHandlerClient) Create(ctx context.Context, in *Integration, opts ...grpc.CallOption) (*Integration, error) {
	out := new(Integration)
	err := c.cc.Invoke(ctx, "/types.IntegrationHandler/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationHandlerClient) Get(ctx context.Context, in *Integration, opts ...grpc.CallOption) (*Integration, error) {
	out := new(Integration)
	err := c.cc.Invoke(ctx, "/types.IntegrationHandler/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationHandlerClient) Delete(ctx context.Context, in *Integration, opts ...grpc.CallOption) (*Integration, error) {
	out := new(Integration)
	err := c.cc.Invoke(ctx, "/types.IntegrationHandler/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationHandlerClient) Update(ctx context.Context, in *Integration, opts ...grpc.CallOption) (*Integration, error) {
	out := new(Integration)
	err := c.cc.Invoke(ctx, "/types.IntegrationHandler/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationHandlerClient) Watch(ctx context.Context, in *Integration, opts ...grpc.CallOption) (IntegrationHandler_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IntegrationHandler_serviceDesc.Streams[0], "/types.IntegrationHandler/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &integrationHandlerWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IntegrationHandler_WatchClient interface {
	Recv() (*Integration, error)
	grpc.ClientStream
}

type integrationHandlerWatchClient struct {
	grpc.ClientStream
}

func (x *integrationHandlerWatchClient) Recv() (*Integration, error) {
	m := new(Integration)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *integrationHandlerClient) CallService(ctx context.Context, in *IntegrationServiceRequest, opts ...grpc.CallOption) (*IntegrationServiceResponse, error) {
	out := new(IntegrationServiceResponse)
	err := c.cc.Invoke(ctx, "/types.IntegrationHandler/CallService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationHandlerClient) WatchService(ctx context.Context, in *Integration, opts ...grpc.CallOption) (IntegrationHandler_WatchServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IntegrationHandler_serviceDesc.Streams[1], "/types.IntegrationHandler/WatchService", opts...)
	if err != nil {
		return nil, err
	}
	x := &integrationHandlerWatchServiceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IntegrationHandler_WatchServiceClient interface {
	Recv() (*IntegrationServiceRequest, error)
	grpc.ClientStream
}

type integrationHandlerWatchServiceClient struct {
	grpc.ClientStream
}

func (x *integrationHandlerWatchServiceClient) Recv() (*IntegrationServiceRequest, error) {
	m := new(IntegrationServiceRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *integrationHandlerClient) StorePut(ctx context.Context, in *IntegrationStoreRequest, opts ...grpc.CallOption) (*IntegrationStoreRequest, error) {
	out := new(IntegrationStoreRequest)
	err := c.cc.Invoke(ctx, "/types.IntegrationHandler/StorePut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationHandlerClient) StoreGet(ctx context.Context, in *IntegrationStoreRequest, opts ...grpc.CallOption) (*IntegrationStoreRequest, error) {
	out := new(IntegrationStoreRequest)
	err := c.cc.Invoke(ctx, "/types.IntegrationHandler/StoreGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationHandlerServer is the server API for IntegrationHandler service.
// All implementations must embed UnimplementedIntegrationHandlerServer
// for forward compatibility
type IntegrationHandlerServer interface {
	Create(context.Context, *Integration) (*Integration, error)
	Get(context.Context, *Integration) (*Integration, error)
	Delete(context.Context, *Integration) (*Integration, error)
	Update(context.Context, *Integration) (*Integration, error)
	Watch(*Integration, IntegrationHandler_WatchServer) error
	CallService(context.Context, *IntegrationServiceRequest) (*IntegrationServiceResponse, error)
	WatchService(*Integration, IntegrationHandler_WatchServiceServer) error
	StorePut(context.Context, *IntegrationStoreRequest) (*IntegrationStoreRequest, error)
	StoreGet(context.Context, *IntegrationStoreRequest) (*IntegrationStoreRequest, error)
	mustEmbedUnimplementedIntegrationHandlerServer()
}

// UnimplementedIntegrationHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedIntegrationHandlerServer struct {
}

func (UnimplementedIntegrationHandlerServer) Create(context.Context, *Integration) (*Integration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedIntegrationHandlerServer) Get(context.Context, *Integration) (*Integration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedIntegrationHandlerServer) Delete(context.Context, *Integration) (*Integration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedIntegrationHandlerServer) Update(context.Context, *Integration) (*Integration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedIntegrationHandlerServer) Watch(*Integration, IntegrationHandler_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedIntegrationHandlerServer) CallService(context.Context, *IntegrationServiceRequest) (*IntegrationServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallService not implemented")
}
func (UnimplementedIntegrationHandlerServer) WatchService(*Integration, IntegrationHandler_WatchServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchService not implemented")
}
func (UnimplementedIntegrationHandlerServer) StorePut(context.Context, *IntegrationStoreRequest) (*IntegrationStoreRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorePut not implemented")
}
func (UnimplementedIntegrationHandlerServer) StoreGet(context.Context, *IntegrationStoreRequest) (*IntegrationStoreRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreGet not implemented")
}
func (UnimplementedIntegrationHandlerServer) mustEmbedUnimplementedIntegrationHandlerServer() {}

// UnsafeIntegrationHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegrationHandlerServer will
// result in compilation errors.
type UnsafeIntegrationHandlerServer interface {
	mustEmbedUnimplementedIntegrationHandlerServer()
}

func RegisterIntegrationHandlerServer(s grpc.ServiceRegistrar, srv IntegrationHandlerServer) {
	s.RegisterService(&_IntegrationHandler_serviceDesc, srv)
}

func _IntegrationHandler_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Integration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationHandlerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.IntegrationHandler/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationHandlerServer).Create(ctx, req.(*Integration))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationHandler_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Integration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationHandlerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.IntegrationHandler/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationHandlerServer).Get(ctx, req.(*Integration))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationHandler_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Integration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationHandlerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.IntegrationHandler/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationHandlerServer).Delete(ctx, req.(*Integration))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationHandler_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Integration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationHandlerServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.IntegrationHandler/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationHandlerServer).Update(ctx, req.(*Integration))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationHandler_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Integration)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IntegrationHandlerServer).Watch(m, &integrationHandlerWatchServer{stream})
}

type IntegrationHandler_WatchServer interface {
	Send(*Integration) error
	grpc.ServerStream
}

type integrationHandlerWatchServer struct {
	grpc.ServerStream
}

func (x *integrationHandlerWatchServer) Send(m *Integration) error {
	return x.ServerStream.SendMsg(m)
}

func _IntegrationHandler_CallService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrationServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationHandlerServer).CallService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.IntegrationHandler/CallService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationHandlerServer).CallService(ctx, req.(*IntegrationServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationHandler_WatchService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Integration)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IntegrationHandlerServer).WatchService(m, &integrationHandlerWatchServiceServer{stream})
}

type IntegrationHandler_WatchServiceServer interface {
	Send(*IntegrationServiceRequest) error
	grpc.ServerStream
}

type integrationHandlerWatchServiceServer struct {
	grpc.ServerStream
}

func (x *integrationHandlerWatchServiceServer) Send(m *IntegrationServiceRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _IntegrationHandler_StorePut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrationStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationHandlerServer).StorePut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.IntegrationHandler/StorePut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationHandlerServer).StorePut(ctx, req.(*IntegrationStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntegrationHandler_StoreGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrationStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationHandlerServer).StoreGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.IntegrationHandler/StoreGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationHandlerServer).StoreGet(ctx, req.(*IntegrationStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IntegrationHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.IntegrationHandler",
	HandlerType: (*IntegrationHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _IntegrationHandler_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _IntegrationHandler_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _IntegrationHandler_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _IntegrationHandler_Update_Handler,
		},
		{
			MethodName: "CallService",
			Handler:    _IntegrationHandler_CallService_Handler,
		},
		{
			MethodName: "StorePut",
			Handler:    _IntegrationHandler_StorePut_Handler,
		},
		{
			MethodName: "StoreGet",
			Handler:    _IntegrationHandler_StoreGet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _IntegrationHandler_Watch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchService",
			Handler:       _IntegrationHandler_WatchService_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "integration.proto",
}
